@RubikCube.Api_HostAddress = https://localhost:7032

GET {{RubikCube.Api_HostAddress}}/api/rubik-cube/state
Accept: application/json

###

POST {{RubikCube.Api_HostAddress}}/api/rubik-cube/rotate/Front
Accept: application/json

###
